name: catweb_parser
description: A new Flutter FFI plugin project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  ffi: ^2.0.2
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:

  ffigen: ^9.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true

ffigen:
  name: CatwebParserBindings
  output: 'lib/catweb_parser_bindings_generated.dart'
  headers:
    entry-points:
      - 'src/ios/catweb_parser.h'
  comments:
    style: any
    length: full